- name: Play Variables
  hosts: localhost # all is not needed we want it to run on local host or same host or workstation in our case
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Play Variables from files
  hosts: localhost # all is not needed we want it to run on local host or same host or workstation in our case
  ## Works only On play level and cannot work on task level
  vars_files:
    - 02.01-vars.yml
  tasks:
    - name: Print Play Variable from File
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play Variables
  hosts: localhost # all is not needed we want it to run on local host or same host or workstation in our case
  tasks:
    - name: Print Play Variable from task
      vars:   # these vars are only for this task , next task on same play cannot access it
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}


- name: Vars from inventory
  hosts: all
  tasks:
    - name: Print Variables from inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }}
## here we are declaring URL variable on our inventory file

- name: Vars from Ansible Facts
  hosts: all
  tasks:
    - name: Print Predefined variables
      ansible.builtin.debug:
        msg: "{{name}} is my name ,  Hostname of server is {{ ansible_hostname  }}"
##i will give url from command line and ansible_hostname is the predefined variable which gives ip
## address of the host .