- name: Play Variables
  hosts: localhost # all is not needed we want it to run on local host or same host or workstation in our case
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      vars:
        ICC: Investing.Coding.Cloud
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      ansible.builtin.debug:
        msg: ICC = {{ ICC }}