- name: Print Parameter
  hosts: localhost
  tasks:
    - name: Print Test1 value
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_ssm' , 'test1' }}" # here test1 is the parameter name 